title: "Elections Utah"
email: utahelectionsproject@gmail.com
description: "Elections Utah is an ongoing, community-driven open data project tracking Utah’s elections."
baseurl: ""
url: "https://www.electionsutah.org"
twitter_username: elections_utah
github_username:  electionsutah
facebook_username: electionsutah

date_format: "%Y-%m-%d"

# Build settings
kramdown:
  input: GFM
permalink: pretty

google_analytics: 'UA-137382505-1'
disqus_shortname: utah-elections-project
comments: true
plugins:
  - jekyll-feed
  # - jekyll-wikidata
exclude:
  - Gemfile
  - Gemfile.lock